# Generated by Django 4.0.6 on 2022-09-23 21:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_games'),
    ]

    operations = [
        migrations.RenameField(
            model_name='games',
            old_name='TotalScore',
            new_name='totalScore',
        ),
    ]
