# Generated by Django 4.0.6 on 2022-09-25 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_games_hintsused'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='roundNumber',
            field=models.IntegerField(default=1),
        ),
    ]
