# Generated by Django 4.0.6 on 2022-10-02 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_games_roundnumber'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
