# Generated by Django 4.1.5 on 2023-01-16 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0009_games_finished'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='myapp.products'),
            preserve_default=False,
        ),
    ]
