# Generated by Django 4.1.5 on 2023-01-16 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0010_games_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='roundNumber',
            field=models.IntegerField(default=0),
        ),
    ]
